### ISSUE TITLE
Status Updates - Phase 1

### ISSUE THREAD

**Issue by JacobWeisenburger** [Royal-Drive/DMS#74]
### Phase 1 - Priority: Critical - DONE
- [x] Add buttons for each status
- [x] Make buttons in same group mutually exclusive
---

### Phase 2 - Priority: Eventually
- [ ] Selecting status sets the date for the associated form section to today
- [ ] Deselecting status sets the date for the associated form section to blank
- [ ] Update Expense Type Names
  - [ ] Labor => Repairs
  - [ ] Transport => In-Transit ?
  - [ ] In-Transit => Transport ?
- [ ] Selecting status shows inputs for associated form section below status buttons
- [ ] Deselecting status hides inputs
- [ ] Sync data to associated form section

---

### Status groups and types
- Work Status
  - In-Transit
  - Onsite Repairs
  - Offsite Repairs
  - Detailing
  - Unassigned
    - = No Work Status & Unlisted
    - Filter only, no status button
- Sale Status
  - Unlisted
  - Listed
  - Sold
  - Sold on Deposit

---

![image](https://user-images.githubusercontent.com/31667350/111395957-0d343200-868c-11eb-9b8b-ce1667e24f3b.png)

**Comment by JacobWeisenburger** [comment]
I'm trying to figure out what to do for the status at the top right of the car details page. Since the car can have a work status and sale status, what do you want to put there?

I could try combining them. example: "Offsite Repairs, 8 DOM". but then that's quite long. Or is that what you think you want?

![image](https://user-images.githubusercontent.com/31667350/113208909-008d0d80-9238-11eb-91ac-c06bb7dfb670.png)

**Comment by RoyalDrive** [comment]
Sure, Offsite Repairs, 8 DOM sounds fine!

**Comment by JacobWeisenburger** [comment]
Phase 2 moved to #83
